### ISSUE TITLE
Test cases are failing

### ISSUE THREAD

**Issue by mschnitzer** [openSUSE/docmanager#76]
A bug has been introduced since https://github.com/openSUSE/docmanager/commit/6797b66b4056c52c8f205d89c38eb3126436691f

```
______________________ test_brokenxml[broken_xml_file.xml] _______________________

tmp_broken_xml = local('/tmp/pytest-754/test_brokenxml_broken_xml_file0/broken_xml_file.xml')

    def test_brokenxml(tmp_broken_xml):
        """Checks the behavior of the XML handler if an exception will be
           thrown when an invalid XML file is given

        :param py.path.local tmp_broken_xml: Fixture, pointing to a temporary
                                             XML file
        """
        with pytest.raises(SystemExit) as err:
>           handler = XmlHandler(tmp_broken_xml.strpath)
E           Failed: DID NOT RAISE

err        = <[AttributeError("'ExceptionInfo' object has no attribute 'typename'") raised in repr()] ExceptionInfo object at 0x7f627e8d9860>
handler    = <docmanager.xmlhandler.XmlHandler object at 0x7f627e8d9eb8>
tmp_broken_xml = local('/tmp/pytest-754/test_brokenxml_broken_xml_file0/broken_xml_file.xml')

test/test_docmanager_brokenxml.py:16: Failed

```
